'use client';
import Link from 'next/link';
import { Check, Gift, Minus, Plus, X } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { api } from '../lib/api';

const fallbackPlans=[
{id:'pro',slug:'pro',name:'PRO',subtitle:'La formule tout-en-un pour accélérer vos processus documentaires et de validation.',monthlyPriceCents:4000000,yearlyPriceCents:44000000,storageGb:500,isHighlighted:false},
{id:'corporate',slug:'corporate',name:'CORPORATE',subtitle:'Pour les organisations qui gèrent des volumes documentaires importants.',monthlyPriceCents:6000000,yearlyPriceCents:60000000,storageGb:1000,badge:'Bestseller',isHighlighted:true},
{id:'sur-mesure',slug:'sur-mesure',name:'SUR MESURE',subtitle:'Au-delà de 1 To, adaptez la capacité de stockage par paliers de 500 Go.',monthlyPriceCents:8000000,yearlyPriceCents:80000000,storageGb:1500,badge:'Flexible',isHighlighted:false},
];
const allowed=new Set(['pro','corporate']);
const base=['Recherche intelligente IA et indexation documentaire','Empreinte SHA-256 et traçabilité','Gestion des dossiers, versions et corbeille','Gestion des utilisateurs et des droits','Accès ordinateur, tablette et smartphone','Signature électronique sécurisée par e-mail','Dossier de preuve de signature','Gestion avancée des droits et groupes','Support prioritaire'];
const plusCorporate=['Signature électronique sécurisée multi-signataires et workflows','Quota de signature configurable','Accès API et intégrations','Accompagnement et support dédiés'];
const plusCustom=['Stockage extensible par paliers de 500 Go','Dimensionnement adapté aux gros volumes','Accompagnement au dimensionnement'];
const compare=[
['Stockage','500 Go','1 To','À partir de 1,5 To'],['Recherche intelligente IA',true,true,true],['Indexation documentaire',true,true,true],['SHA-256 et traçabilité',true,true,true],['Dossiers, versions et corbeille',true,true,true],['Signature électronique sécurisée',true,true,true],['Dossier de preuve',true,true,true],['Droits et groupes avancés',true,true,true],['Multi-signataires et workflows',false,true,true],['API et intégrations',false,true,true],['Support','Prioritaire','Dédié','Dédié']
] as const;
function slug(p:any){return String(p.slug||p.name||'').toLowerCase()}
function fcfa(c?:number|null){return c==null?'Sur devis':`${Math.round(c/100).toLocaleString('fr-FR')} FCFA HT`}
function freeMonths(p:any){return slug(p)==='pro'?1:2}
function features(p:any){return slug(p)==='sur-mesure'?[...base,...plusCorporate,...plusCustom]:slug(p)==='corporate'?[...base,...plusCorporate]:base}
function mark(v:boolean|string){return v===true?<Check size={18} style={{color:'#18794e'}}/>:v===false?<X size={18} style={{color:'#b42318'}}/>:<span>{v}</span>}
function normalizePlans(items:any[]){
  const normalized=items.filter((p:any)=>allowed.has(slug(p))).map((p:any)=>{
    const s=slug(p);
    if(s==='pro')return {...p,name:'PRO',monthlyPriceCents:4000000,yearlyPriceCents:44000000,storageGb:500,badge:null,isHighlighted:false};
    return {...p,name:'CORPORATE',monthlyPriceCents:6000000,yearlyPriceCents:60000000,storageGb:1000,badge:'Bestseller',isHighlighted:true};
  });
  return [...normalized,{...fallbackPlans[2]}];
}
export function SubscriptionPricing(){
const[plans,setPlans]=useState<any[]>([]);const[selectedSlug,setSelectedSlug]=useState('');const[billing,setBilling]=useState<'monthly'|'yearly'>('monthly');const[initialized,setInitialized]=useState(false);const[customStorageGb,setCustomStorageGb]=useState(1500);const choiceRef=useRef<HTMLDivElement|null>(null);
useEffect(()=>{api('/marketing/public/plans').then((items:any[])=>setPlans(normalizePlans(items))).catch(()=>setPlans(fallbackPlans));const q=new URLSearchParams(window.location.search);setSelectedSlug(q.get('plan')||'');setBilling(q.get('billing')==='yearly'?'yearly':'monthly');const requestedStorage=Number(q.get('storageGb')||1500);if(Number.isFinite(requestedStorage)&&requestedStorage>=1500)setCustomStorageGb(Math.ceil(requestedStorage/500)*500);setInitialized(true)},[]);
const displayPlans=plans.length?plans:fallbackPlans;const selected=useMemo(()=>displayPlans.find((p:any)=>slug(p)===selectedSlug.toLowerCase()),[displayPlans,selectedSlug]);
const customSteps=Math.max(1,(customStorageGb-1000)/500);const customMonthlyCents=6000000+customSteps*2000000;const customYearlyCents=customMonthlyCents*10;
const selectedMonthlyCents=selected&&slug(selected)==='sur-mesure'?customMonthlyCents:selected?.monthlyPriceCents;const selectedYearlyCents=selected&&slug(selected)==='sur-mesure'?customYearlyCents:selected?.yearlyPriceCents;
useEffect(()=>{if(initialized&&selectedSlug&&selected){const t=setTimeout(()=>choiceRef.current?.scrollIntoView({behavior:'smooth',block:'center'}),150);return()=>clearTimeout(t)}},[initialized,selectedSlug,selected]);
function choose(p:any){setSelectedSlug(p.slug||p.name);setBilling('monthly');if(slug(p)==='sur-mesure')setCustomStorageGb(v=>Math.max(1500,v));setTimeout(()=>choiceRef.current?.scrollIntoView({behavior:'smooth',block:'center'}),50)}
function storageLabel(gb:number){return gb%1000===0?`${gb/1000} To`:`${(gb/1000).toLocaleString('fr-FR',{maximumFractionDigits:1})} To`}
return <>
<section className="section"><div className="publicContainer"><div className="subscriptionSteps"><span className="active">1. Pack</span><span>2. Périodicité</span><span>3. Conditions</span><span>4. Souscription</span></div><div className="pricingGrid subscriptionPricingGrid">{displayPlans.map((p:any)=>{const s=slug(p);const chosen=selected&&slug(selected)===s;const shownPrice=s==='sur-mesure'?8000000:p.monthlyPriceCents;return <article key={p.id||p.name} className={`priceCard subscriptionPriceCard ${p.isHighlighted?'featured':''} ${chosen?'selectedPlan':''}`}>{p.badge&&<span className="planBadge">{p.badge}</span>}<div className="priceName">{p.name}</div><p>{p.subtitle}</p><div className={`priceAmount priceAmountInline ${s==='sur-mesure'?'priceAmountCustom':''}`}><span>{s==='sur-mesure'?'À partir de ':''}{fcfa(shownPrice)}</span><small>/ mois</small></div><div className="planMeta">{s==='sur-mesure'?'Plus de 1 To · paliers de 500 Go':p.storageGb>=1000?'1 To de stockage':`${p.storageGb} Go de stockage`}</div>{s!=='pro'&&<div style={{fontWeight:800,margin:'16px 0 8px'}}>{s==='corporate'?'Tout PRO +':'Tout CORPORATE +'}</div>}<ul className="priceList subscriptionFeatureList" style={{listStyle:'none',paddingLeft:0}}>{features(p).map(x=><li key={x}>{x}</li>)}</ul><button type="button" onClick={()=>choose(p)} className={p.isHighlighted?'publicPrimary':'publicSecondary'}>{chosen?'Pack sélectionné':'Choisir ce pack'}</button></article>})}</div></div></section>
<section className="section sectionAlt"><div className="publicContainer"><span className="eyebrow">Comparatif</span><h2>Comparez les packs Coffria</h2><p>PRO démarre à 500 Go, CORPORATE inclut 1 To et l’offre SUR MESURE permet d’ajouter de la capacité par paliers de 500 Go.</p><div style={{overflowX:'auto',background:'#fff',border:'1px solid #d9dee7',borderRadius:14}}><table style={{width:'100%',minWidth:720,borderCollapse:'collapse'}}><thead><tr><th style={{textAlign:'left',padding:16}}>Fonctionnalité</th><th>PRO</th><th>CORPORATE</th><th>SUR MESURE</th></tr></thead><tbody>{compare.map(r=><tr key={r[0]} style={{borderTop:'1px solid #edf0f4'}}><td style={{padding:14,fontWeight:650}}>{r[0]}</td><td style={{padding:14,textAlign:'center'}}>{mark(r[1])}</td><td style={{padding:14,textAlign:'center'}}>{mark(r[2])}</td><td style={{padding:14,textAlign:'center'}}>{mark(r[3])}</td></tr>)}</tbody></table></div></div></section>
{selected&&<section className="section" ref={choiceRef}><div className="publicContainer billingChoice"><div><span className="eyebrow">Étape 2 sur 4</span><h2>Configurez le Pack {selected.name}</h2>{slug(selected)==='sur-mesure'?<><p>Le tarif part de 60 000 FCFA HT pour 1 To, puis ajoute 20 000 FCFA HT par palier supplémentaire de 500 Go.</p><div style={{display:'flex',alignItems:'center',gap:14,flexWrap:'wrap',marginTop:18}}><button type="button" className="publicSecondary" aria-label="Retirer 500 Go" disabled={customStorageGb<=1500} onClick={()=>setCustomStorageGb(v=>Math.max(1500,v-500))}><Minus size={17}/></button><div style={{minWidth:180,textAlign:'center',padding:'14px 20px',border:'1px solid #d9dee7',borderRadius:12,background:'#fff'}}><strong style={{display:'block',fontSize:24}}>{storageLabel(customStorageGb)}</strong><span className="muted">Stockage choisi</span></div><button type="button" className="publicSecondary" aria-label="Ajouter 500 Go" onClick={()=>setCustomStorageGb(v=>v+500)}><Plus size={17}/></button><div style={{fontWeight:800,fontSize:20}}>{fcfa(customMonthlyCents)} / mois</div></div></>:<p>Le paiement annuel inclut {freeMonths(selected)} mois offert{freeMonths(selected)>1?'s':''}.</p>}</div><div className="billingOptions"><button type="button" className={billing==='monthly'?'billingOption active':'billingOption'} onClick={()=>setBilling('monthly')}><span>Mensuel</span><strong>{fcfa(selectedMonthlyCents)}</strong><small>Facturé chaque mois</small></button><button type="button" className={billing==='yearly'?'billingOption active':'billingOption'} onClick={()=>setBilling('yearly')}><span>Annuel</span><strong>{fcfa(selectedYearlyCents)}</strong><small><Gift size={15}/> {freeMonths(selected)} mois offert{freeMonths(selected)>1?'s':''}</small></button></div><div className="billingContinue"><Link className="publicPrimary" href={`/conditions?plan=${encodeURIComponent(selected.slug||selected.name)}&billing=${billing}${slug(selected)==='sur-mesure'?`&storageGb=${customStorageGb}&price=${billing==='yearly'?Math.round(customYearlyCents/100):Math.round(customMonthlyCents/100)}`:''}`}>Continuer vers les conditions</Link><button type="button" className="publicSecondary" onClick={()=>setSelectedSlug('')}>Changer de pack</button></div></div></section>}
</>}
